{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMaPjMvbQxh4/QNuhu2GiQz",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Juarlex/Juarlex/blob/main/Particle.sim.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 15,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "yatTQ81O2FDa",
        "outputId": "d088e3d8-0aeb-4565-d47c-bcc72038a7b8"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "============================================================\n",
            "  PARTICLE MOTION SIMULATOR\n",
            "============================================================\n",
            "  Particle : Projectile (45° launch)\n",
            "  Mass     : 2.0 kg\n",
            "  Start    : (0.00, 0.00) m\n",
            "  Velocity : vx=14.14, vy=14.14 m/s\n",
            "  Gravity  : 9.81 m/s²\n",
            "============================================================\n",
            "\n",
            "Time(s)    X(m)       Y(m)       Speed(m/s)   KE(J)      PE(J)      Total E(J)\n",
            "------------------------------------------------------------------------\n",
            "0.00       0.00       0.00       20.000       400.00     0.00       400.00    \n",
            "0.50       7.07       5.82       16.892       285.32     114.19     399.52    \n",
            "1.00       14.14      9.19       14.791       218.77     180.27     399.04    \n",
            "1.50       21.21      10.10      14.154       200.33     198.23     398.56    \n",
            "2.00       28.28      8.57       15.166       230.01     168.07     398.08    \n",
            "2.50       35.36      4.58       17.544       307.80     89.79      397.59    \n",
            "\n",
            "  >>> Particle hit the ground at t = 2.88s\n",
            "\n",
            "============================================================\n",
            "  SIMULATION SUMMARY\n",
            "============================================================\n",
            "  Max height reached : 10.12 m (at t=1.44s)\n",
            "  Max speed reached  : 20.000 m/s\n",
            "  Total time elapsed : 2.88 s\n",
            "  Trajectory points  : 289\n",
            "============================================================\n",
            "\n",
            "  PHYSICS INSIGHTS:\n",
            "  - Energy is conserved throughout (Total E ≈ constant)\n",
            "  - At peak height, all energy is potential energy\n",
            "  - At ground level, all energy is kinetic energy\n",
            "  - This is Newton's classical mechanics in action!\n",
            "\n",
            "\n",
            "============================================================\n",
            "  PARTICLE MOTION SIMULATOR\n",
            "============================================================\n",
            "  Particle : Free Fall from 100m\n",
            "  Mass     : 1.0 kg\n",
            "  Start    : (0.00, 100.00) m\n",
            "  Velocity : vx=0.00, vy=0.00 m/s\n",
            "  Gravity  : 9.81 m/s²\n",
            "============================================================\n",
            "\n",
            "Time(s)    X(m)       Y(m)       Speed(m/s)   KE(J)      PE(J)      Total E(J)\n",
            "------------------------------------------------------------------------\n",
            "0.00       0.00       100.00     0.000        0.00       981.00     981.00    \n",
            "0.50       0.00       98.75      4.905        12.03      968.73     980.76    \n",
            "1.00       0.00       95.05      9.810        48.12      932.40     980.52    \n",
            "1.50       0.00       88.89      14.715       108.27     872.01     980.28    \n",
            "2.00       0.00       80.28      19.620       192.47     787.57     980.04    \n",
            "2.50       0.00       69.22      24.525       300.74     679.06     979.80    \n",
            "3.00       0.00       55.71      29.430       433.06     546.49     979.56    \n",
            "3.50       0.00       39.74      34.335       589.45     389.87     979.32    \n",
            "4.00       0.00       21.32      39.240       769.89     209.19     979.08    \n",
            "4.50       0.00       0.45       44.145       974.39     4.44       978.83    \n",
            "\n",
            "  >>> Particle hit the ground at t = 4.52s\n",
            "\n",
            "============================================================\n",
            "  SIMULATION SUMMARY\n",
            "============================================================\n",
            "  Max height reached : 100.00 m (at t=0.00s)\n",
            "  Max speed reached  : 44.243 m/s\n",
            "  Total time elapsed : 4.52 s\n",
            "  Trajectory points  : 453\n",
            "============================================================\n",
            "\n",
            "  PHYSICS INSIGHTS:\n",
            "  - Energy is conserved throughout (Total E ≈ constant)\n",
            "  - At peak height, all energy is potential energy\n",
            "  - At ground level, all energy is kinetic energy\n",
            "  - This is Newton's classical mechanics in action!\n",
            "\n",
            "\n",
            "============================================================\n",
            "  PARTICLE MOTION SIMULATOR\n",
            "============================================================\n",
            "  Particle : Horizontal Throw from 50m\n",
            "  Mass     : 0.5 kg\n",
            "  Start    : (0.00, 50.00) m\n",
            "  Velocity : vx=15.00, vy=0.00 m/s\n",
            "  Gravity  : 9.81 m/s²\n",
            "============================================================\n",
            "\n",
            "Time(s)    X(m)       Y(m)       Speed(m/s)   KE(J)      PE(J)      Total E(J)\n",
            "------------------------------------------------------------------------\n",
            "0.00       0.00       50.00      15.000       56.25      245.25     301.50    \n",
            "0.50       7.50       48.75      15.782       62.26      239.11     301.38    \n",
            "1.00       15.00      45.05      17.923       80.31      220.95     301.26    \n",
            "1.50       22.50      38.89      21.013       110.38     190.76     301.14    \n",
            "2.00       30.00      30.28      24.697       152.49     148.53     301.02    \n",
            "2.50       37.50      19.22      28.748       206.62     94.28      300.90    \n",
            "3.00       45.00      5.71       33.032       272.78     28.00      300.78    \n",
            "\n",
            "  >>> Particle hit the ground at t = 3.19s\n",
            "\n",
            "============================================================\n",
            "  SIMULATION SUMMARY\n",
            "============================================================\n",
            "  Max height reached : 50.00 m (at t=0.00s)\n",
            "  Max speed reached  : 34.615 m/s\n",
            "  Total time elapsed : 3.19 s\n",
            "  Trajectory points  : 320\n",
            "============================================================\n",
            "\n",
            "  PHYSICS INSIGHTS:\n",
            "  - Energy is conserved throughout (Total E ≈ constant)\n",
            "  - At peak height, all energy is potential energy\n",
            "  - At ground level, all energy is kinetic energy\n",
            "  - This is Newton's classical mechanics in action!\n",
            "\n"
          ]
        }
      ],
      "source": [
        "import math\n",
        "\n",
        "# Constants\n",
        "G = 9.81  # gravity (m/s^2)\n",
        "DT = 0.01  # time step (seconds)\n",
        "\n",
        "class Particle:\n",
        "    def __init__(self, x, y, vx, vy, mass=1.0, name=\"Particle\"):\n",
        "        self.x = x\n",
        "        self.y = y\n",
        "        self.vx = vx\n",
        "        self.vy = vy\n",
        "        self.mass = mass\n",
        "        self.name = name\n",
        "        self.trajectory = [(x, y)]\n",
        "        self.time = 0\n",
        "\n",
        "    def update(self):\n",
        "        \"\"\"Update position and velocity using Euler integration\"\"\"\n",
        "        # Apply gravity\n",
        "        ay = -G  # acceleration in y (downward)\n",
        "        ax = 0   # no horizontal acceleration\n",
        "\n",
        "        # Update velocity\n",
        "        self.vx += ax * DT\n",
        "        self.vy += ay * DT\n",
        "\n",
        "        # Update position\n",
        "        self.x += self.vx * DT\n",
        "        self.y += self.vy * DT\n",
        "\n",
        "        self.time += DT\n",
        "        self.trajectory.append((self.x, self.y))\n",
        "\n",
        "    def kinetic_energy(self):\n",
        "        v_squared = self.vx**2 + self.vy**2\n",
        "        return 0.5 * self.mass * v_squared\n",
        "\n",
        "    def potential_energy(self):\n",
        "        return self.mass * G * self.y\n",
        "\n",
        "    def total_energy(self):\n",
        "        return self.kinetic_energy() + self.potential_energy()\n",
        "\n",
        "    def speed(self):\n",
        "        return math.sqrt(self.vx**2 + self.vy**2)\n",
        "\n",
        "\n",
        "def simulate(particle, duration=5.0, ground_y=0.0):\n",
        "    \"\"\"Run simulation until duration or particle hits ground\"\"\"\n",
        "    steps = int(duration / DT)\n",
        "    print(f\"\\n{'='*60}\")\n",
        "    print(f\"  PARTICLE MOTION SIMULATOR\")\n",
        "    print(f\"{'='*60}\")\n",
        "    print(f\"  Particle : {particle.name}\")\n",
        "    print(f\"  Mass     : {particle.mass} kg\")\n",
        "    print(f\"  Start    : ({particle.x:.2f}, {particle.y:.2f}) m\")\n",
        "    print(f\"  Velocity : vx={particle.vx:.2f}, vy={particle.vy:.2f} m/s\")\n",
        "    print(f\"  Gravity  : {G} m/s²\")\n",
        "    print(f\"{'='*60}\\n\")\n",
        "\n",
        "    print(f\"{'Time(s)':<10} {'X(m)':<10} {'Y(m)':<10} {'Speed(m/s)':<12} {'KE(J)':<10} {'PE(J)':<10} {'Total E(J)':<10}\")\n",
        "    print(f\"{'-'*72}\")\n",
        "\n",
        "    max_height = particle.y\n",
        "    max_speed = particle.speed()\n",
        "    peak_time = 0\n",
        "\n",
        "    for i in range(steps):\n",
        "        # Print every 0.5 seconds\n",
        "        if i % 50 == 0:\n",
        "            ke = particle.kinetic_energy()\n",
        "            pe = particle.potential_energy()\n",
        "            te = particle.total_energy()\n",
        "            print(f\"{particle.time:<10.2f} {particle.x:<10.2f} {particle.y:<10.2f} {particle.speed():<12.3f} {ke:<10.2f} {pe:<10.2f} {te:<10.2f}\")\n",
        "\n",
        "        # Track max height\n",
        "        if particle.y > max_height:\n",
        "            max_height = particle.y\n",
        "            peak_time = particle.time\n",
        "\n",
        "        # Track max speed\n",
        "        if particle.speed() > max_speed:\n",
        "            max_speed = particle.speed()\n",
        "\n",
        "        particle.update()\n",
        "\n",
        "        # Stop if particle hits ground\n",
        "        if particle.y <= ground_y and particle.time > 0.1:\n",
        "            print(f\"\\n  >>> Particle hit the ground at t = {particle.time:.2f}s\")\n",
        "            break\n",
        "\n",
        "    print(f\"\\n{'='*60}\")\n",
        "    print(f\"  SIMULATION SUMMARY\")\n",
        "    print(f\"{'='*60}\")\n",
        "    print(f\"  Max height reached : {max_height:.2f} m (at t={peak_time:.2f}s)\")\n",
        "    print(f\"  Max speed reached  : {max_speed:.3f} m/s\")\n",
        "    print(f\"  Total time elapsed : {particle.time:.2f} s\")\n",
        "    print(f\"  Trajectory points  : {len(particle.trajectory)}\")\n",
        "    print(f\"{'='*60}\\n\")\n",
        "\n",
        "    # Physics insight\n",
        "    print(\"  PHYSICS INSIGHTS:\")\n",
        "    print(f\"  - Energy is conserved throughout (Total E ≈ constant)\")\n",
        "    print(f\"  - At peak height, all energy is potential energy\")\n",
        "    print(f\"  - At ground level, all energy is kinetic energy\")\n",
        "    print(f\"  - This is Newton's classical mechanics in action!\\n\")\n",
        "\n",
        "\n",
        "# --- Run different scenarios ---\n",
        "\n",
        "# Scenario 1: Projectile launched at 45 degrees (optimal range angle)\n",
        "v0 = 20  # initial speed in m/s\n",
        "angle = 45  # degrees\n",
        "vx = v0 * math.cos(math.radians(angle))\n",
        "vy = v0 * math.sin(math.radians(angle))\n",
        "\n",
        "p1 = Particle(x=0, y=0, vx=vx, vy=vy, mass=2.0, name=\"Projectile (45° launch)\")\n",
        "simulate(p1, duration=10.0)\n",
        "\n",
        "# Scenario 2: Ball dropped from height\n",
        "p2 = Particle(x=0, y=100, vx=0, vy=0, mass=1.0, name=\"Free Fall from 100m\")\n",
        "simulate(p2, duration=10.0)\n",
        "\n",
        "# Scenario 3: Horizontal throw\n",
        "p3 = Particle(x=0, y=50, vx=15, vy=0, mass=0.5, name=\"Horizontal Throw from 50m\")\n",
        "simulate(p3, duration=10.0)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "df9d8368"
      },
      "source": [
        "# Task\n",
        "Fix the f-string syntax in the print statement within the `simulate` function by changing a semicolon to a colon. Correct the indentation for the `update`, `kinetic_energy`, `potential_energy`, `total_energy`, and `speed` methods so they are properly nested within the `Particle` class. Move the `simulate` function outside the `Particle` class. Replace `seld.vx` with `self.vx` and `particlet.y` with `particle.y`. Change `math.radian` to `math.radians`. Adjust the `speed` method to use `self.vx**2` instead of `self.vx**3`. Correct the variable `p2` to `p1` in the first scenario call to `simulate`. Change the incorrect `print(f\"\\n{'n'*60}\")` to `print(f\"\\n{'='*60}\")` for the simulation summary separator. Also, correct the f-string in the `simulate` function's start print, and update the print statement for energy values to include `pe`. Finally, execute the corrected Python code."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "e67d6ef2"
      },
      "source": [
        "## Fix f-string syntax\n",
        "\n",
        "### Subtask:\n",
        "Correct the f-string syntax in the `print` statement by replacing the semicolon with a colon for formatting.\n"
      ]
    }
  ]
}